replicaCount: 2

containers:
  image:
    repository: httpd:2.4
    pullPolicy: IfNotPresent
  containerPort: 80
  volumeMounts:
    name: web-template
    mountPath: /usr/local/apache2/htdocs/
  
initContainers:
  git:
    repository: alpine/git
    pullPolicy: IfNotPresent
  cloneHtdocsFromGit:
    
    VolumeMounts:
      name: web-template
      

service:
  type: ClusterIP
  port: 80
  name: port-web-apache
  targetPort: 80

