apiVersion: v1
kind: Service
metadata:
  name: svc-web-apache
spec:
  selector:
    name: web-apache
  ports:
    - name: {{ .Values.service.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type}}