apiVersion: v1
kind: Service
metadata:
  name: svc-web-apache
  namespace: default
spec:
  selector:
    app: apache-ssl
  ports:
    - name: port-web-apache
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer